### ISSUE TITLE
Replay API Implementation

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#128]
**Describe the solution you'd like**
Using the recently added battle record model, what'd I would picture this is what is needed:
- API to get the battle record to replay
    - Gets by its id
- API to get list of battle records
    - Gets the list based off the user

**Describe alternatives you've considered**
N/A

**Additional context**
If anyone can give a good description of what I need here, it would be appreciated.

**Comment by blaiadam** [comment]
The information needed to show Replays to users:

User:
- Tank Name
- Tank Components
- Tank's Casus Code
- Currency Won/Lossed
- Whether User Won/Loss
- Elo Gained/Lossed

Opponent:
- Tank Name
- Tank Components
- Tank's Casus Code
- Currency Won/Lossed
- Whether User Won/Loss
- Elo Gained/Lossed

Let me know if there is any questions.
