### ISSUE TITLE
Testing. Seems straightforward enough.

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#129]
**Describe the solution you'd like**
We're all aware, we don't any any form of testing currently done. So obviously this needs to be done, or at least a framework of how we are going to do it should be discussed and documented. This is just a general issue for it so this topic can stay in mind for us since we're all still developing. Separate issues can be created for specific tasking when the time comes.

**Describe alternatives you've considered**
Have you heard of any mainstream application that NEVER had any testing done with it?

**Additional context**
N/A

**Comment by SecondThread** [comment]
Jest is decent
https://jestjs.io/

**Comment by Derplime** [comment]
> Jest is decent
> https://jestjs.io/

Yeah I was thinking the same. I'm just not familiar with using it. Though I have no issue learning how to when we have the opportunity to.
