### ISSUE TITLE
Master doesn't pass Flow

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#134]
**Describe the bug**
Master fails to pass flow.

**To Reproduce**
1. Use 'npm run flow'
2. See error.

**Expected behavior**
Should pass flow.

**Screenshots**
![Screenshot (32)](https://user-images.githubusercontent.com/42626045/76231250-58a33d00-61fb-11ea-9203-7625f517babc.png)
![Screenshot (33)](https://user-images.githubusercontent.com/42626045/76231251-593bd380-61fb-11ea-99e9-119bd17628d4.png)
![Screenshot (34)](https://user-images.githubusercontent.com/42626045/76231253-593bd380-61fb-11ea-8699-9584a1eaed76.png)

**Additional context**
N/A

**Comment by SecondThread** [comment]
!!!
