### ISSUE TITLE
Armory crashes when loaded after a successful login

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#144]
**Describe the bug**
This error message appears after a successful login at the armory:
![image](https://user-images.githubusercontent.com/18317476/76450529-54665380-63a4-11ea-8286-40471fe926ce.png)

**To Reproduce**
1. Log in as a user
2. Go to the armory
3. Wait like a second

**Expected behavior**
idk, but it shouldn't have any errors

**Screenshots**
Screenshot above

**Additional context**

**Comment by blaiadam** [comment]
This is fixed.
