### ISSUE TITLE
No response from API call when the login token isn't provided

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#157]
**Describe the bug**
Everything works fine when the x-auth-token is provided in the header. When the x-auth-token isn't (and possibly when it is but is incorrect), there is just no response to the front end. This makes error handling really hard.

**To Reproduce**
1. Call saveCasus for example but comment out the part about the x-auth-token

**Expected behavior**
Some sort of error or something saying that the auth token is invalid.

**Screenshots**

**Additional context**

**Comment by Airor4** [comment]
Is this the /casusUpdate api call you're talking about because every api call with auth middleware i see has token error handling?

**Comment by SecondThread** [comment]
TODO: talk with baylor after the meeting

**Comment by Airor4** [comment]
That particular route didn't have authentication on it. It has since been added
