### ISSUE TITLE
Update tank needs to also update inventory

### ISSUE THREAD

**Issue by Airor4** [RickLeinecker/Fortuna#165]
**Describe the bug**
Components are added to the tank without any change to the inventory meaning people can continuously add parts to their tank that should be unavailable when equipped by another tank.

**To Reproduce**
1. call update tank api with a component to equip and the inventory remains the same.

**Expected behavior**

**Screenshots**
N/a

**Additional context**
N/a

**Comment by Derplime** [comment]
This probably will tie in with #240
