### ISSUE TITLE
Ideas for Professors for Committee

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#18]
We already had made progress on this, so we can just add what we had to the issue when we can.

Arup said as a general rule of thumb he would as long as he isn't busy whenever the presentation is.

**Comment by Derplime** [comment]
Jorge reached out to Carbone. David will ask Guha.

**Comment by Derplime** [comment]
Emil will ask someone from work. (Alumni)

**Comment by Derplime** [comment]
1/20 update

Guha: Just let him know (Ok)
Carbone: Follow up on Spring Break
Kathy (Emil): Have to finalize and confirm

**Comment by Derplime** [comment]
Update: I wasn't able to get my person to come. So we'll still need a third person.

**Comment by Derplime** [comment]
Update:
Tom Carbone (@JorgeVidal29): Confirmed?
Sarah Angell (@JorgeVidal29): Emailed
Arup Guha (@SecondThread): Confirmed
Travis Meade (@SecondThread): Emailed

**Comment by Derplime** [comment]
Confirmed for 4/20 at 5pm
Finalize list of staff coming at meeting tomorrow before closing this.

**Comment by blaiadam** [comment]
Confirmed for 4/20 at 5pm with Guha, Carbone, and Leinecker.
