### ISSUE TITLE
Make email confirmation great again

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#204]
**Describe the bug**
The page is simple and should redirect people back to Fortuna's website.

**To Reproduce**
1. Confirm your email.
2. View the simple page and laugh.

**Expected behavior**
Should route you to our website, and look better.

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/76899243-888eb800-686d-11ea-8f81-82d0d30fe72f.png)

**Additional context**
N/A

**Comment by Derplime** [comment]
> Confirm your email.
> View the simple page and laugh.
> @blaiadam 

@Zexdur Adam's calling you out bro
