### ISSUE TITLE
Can still "login" as a deleted user.

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#205]
**Describe the bug**
So this likely has to do with how we deal with cookies when you're not on the Fortuna site, or if you close your browser without logging out. Didn't try if running in incognito/private browsing would result in a different thing, but based on the nature of those modes for browsing, you wouldn't be able to reproduce this on them.

**To Reproduce**
On Fortuna site with a non-private browser (browser not in "Private-Browsing" mode) done locally
1. Register a new user & verify them so they can login.
2. Login as that user.
3. Close browser without logging out
4. Delete user from DB
5. Open browser and go back to Fortuna site and press "Login"
6. View that you login as the deleted user. You also hit a frontend error since you can't draw info from a deleted user's cookie.
7. Go back to home page and press "Login".
8. Step 6-7 repeats. Congratulations! We're stuck in a loop without being able to clear cookies unless you do it via the browser settings.

**Expected behavior**
Not sure how this can be handled, but this is just something to be aware of if anything. Maybe if something like this happens, whatever cookie was there is erased and they're redirected to the home page, or the cookie is erased and the login pop up works as normal. Both cases can just have a specific dialog prompt giving some notification of being unable to login with that account anymore.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by SecondThread** [comment]
This is caused by the same thing as the reason I rejected PR #193. Before actually logging in, we need to verify that the login cookie is valid, which we currently aren't doing.

**Comment by Derplime** [comment]
Guess this has to be re-verified once #195 gets merged.
