### ISSUE TITLE
Run through current API and add error handling to "silently failing" calls + some refactoring

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#213]
**Describe the solution you'd like**
Do a clean run through the currently implemented API and update any error handling, and other things.

casusController:
* Add default case to the switch

marketController:
* Actually `return`ing responses down the line

replayController:
* Remove unused dependencies
* Actually `return`ing responses down the line

tankController:
* Add error validation to some DB calls in casusUpdate, tankUpdate, assignTank
* Actually `return`ing responses down the line

userController:
* Add error validation to DB calls down the line
* Remove unused dependencies
* `return`ing responses down the line

auth;
* `return`ing responses down the line

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SecondThread** [comment]
Can we get a list of which calls are silent? This seems pretty ill-defined at the moment

**Comment by Derplime** [comment]
> Can we get a list of which calls are silent? This seems pretty ill-defined at the moment

Updated body going over what I'm covering
