### ISSUE TITLE
Login CSS looks bad on small screens

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#250]
**Describe the bug**
Here's a picture of what this looks like on my laptop:
![image](https://user-images.githubusercontent.com/18317476/77667230-4e51a480-6f58-11ea-9947-34d0d02aae18.png)

**To Reproduce**
1. Create a new user, do not register him, and try to login with him

**Expected behavior**
Text and buttons should not overlap.

**Comment by blaiadam** [comment]
This needs to be fixed by implementing toast messages.
