### ISSUE TITLE
When you create a new tank, the chassis/treads are Empty

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#269]
**Describe the bug**
After creating a new tank, the chassis and treads for it are empty by default.

**To Reproduce**
1. Go to the armory.
2. Click "Create" under Create a new Tank
3. Choose Modable Light and Advanced Treads, -> Create

You will get a tank that looks like this:
![image](https://user-images.githubusercontent.com/18317476/77808996-28192b00-7064-11ea-9df6-de87a5608b02.png)

**Expected behavior**
The tank should have the treads and chassis that you selected showing

**Comment by blaiadam** [comment]
I'll check it out right now.

**Comment by Derplime** [comment]
No issue for me
![Armory2](https://user-images.githubusercontent.com/24559442/77809125-b8577000-7064-11ea-9fe4-99e1cc947a43.gif)

**Comment by SecondThread** [comment]
user error
