### ISSUE TITLE
Pricing Distribution for Components and other Money Talk (Low Priority)

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#274]
**Describe the solution you'd like**
Just decide a pricing distribution for components. This is more for the sales on the actual website than anything. It isn't high of a priority, but one we should keep here to remind ourselves.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SecondThread** [comment]
Here is my suggestion for initial money balancing:
Give players $100 when they create a wager for the first time in 8 hours
Make players start with $400 by default.

Weapons:
- Machine gun: $50
- Grenade Launcher: $80
- Missile: $120
- Shotgun: $80
- Vulcan Cannon: $300
- Laser: $300
- Plasma: $130
- Lancer: $250
- Death Ray: $275

Scanners:
- Short Range: $100
- Medium Range: $250
- Long Range: $750

Chassis:
- Moddable Light: $300
- Light: $400
- Moddable: $200
- Heavy: $400
- Moddable Heavy: $300

Jammers:
- Short Range: $300
- Medium Range: $400
- Long Range: $500

Treads:
- Advanced Treads: $200
- Fast Treads: $100
- Armored Treads: $100
-Heavily Armored Treads: $200

Scanner Addons:
ItemScanner: $200
Anti-Jammer: $500

Accessories:
Mine: $80
C4: $150
Nitro Repair: $200
Overdrive: $200
Missile Tracking Beacon: $300


We can fix things after if that winds up not working well

**Comment by SecondThread** [comment]
Unassigned myself since you have my input

**Comment by Derplime** [comment]
My thoughts:
- Rather make it a match related stipend than a wager related stipend;
  - Forces people to battle others (and affect their own elo)
  - Can do something like first match of the day / first win of the day
    - First win bonus can be an incentive to keep battling (risky though if you can't win at least once)
    - First match is more new player friendly

**Comment by SecondThread** [comment]
Assigned to Emil to actually implement these changes on the backend/server et cetera

**Comment by SecondThread** [comment]
*also change min wager amount to ~$50

**Comment by blaiadam** [comment]
Change the wager daily stipend to 100 and make the first first win of the day 100, second 200, and third 300 (they have to win 3 days in a row to get to the 300). If you feel these values can be changed, feel free to change them.

**Comment by Derplime** [comment]
Updated the marketplace listings backup on the drive. Working on editing the wager daily and making an API for the wins of the day.
