### ISSUE TITLE
Send Leinecker an email asking about expectations for our demo on Monday

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#278]
**Describe the solution you'd like**
Send Dr. Leinecker an email asking about how formal the Leinecker demo is suppose to be. Include:
- Should we have slides?
- How long is the demo?
- Are there any important grading criteria?
- Would he want us to show the version on fortunacombat.com, or can we show our local versions?
- Is one of us driving or is he?

**Comment by Derplime** [comment]
DEMO BE DONE. THE OFFERING TO LEINECKER IS COMPLETE. HE WAS PLEASED.
