### ISSUE TITLE
Connect Login with Login Api

### ISSUE THREAD

**Issue by JorgeVidal29** [RickLeinecker/Fortuna#29]
The login page needs to call the login api and then move on depending on the response. It also needs to have a username and password field.

**Comment by Airor4** [comment]
I successfully hit the api from the frontend using a proxy. The frontend should be listening on the port 3000 by default and I set the backend to listen on port 3001. Using the proxy you dont need to use the entire url of the backend. for example: const response = await fetch('/user/newUser' which is the route to register a new user.

**Comment by Airor4** [comment]
Successfully hooked up the login and register api to the react front-end through proxy!
