### ISSUE TITLE
Hardcode the training bot id's to the front end in the training arena

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#290]
**Describe the solution you'd like**
Currently the training bots have been created, but there is just placeholder text on the front end for what they actually are. This PR is to hardcode their IDs on the frontend so that when the user challenges them it starts a battle between the correct tank.

This also includes making changing the Battleground to be able to start a match given two tank ids, instead of a match id.

**Comment by Derplime** [comment]
So to help with that, you can use the DB backup tanks. The file itself will be updated to reflect a new Master account due to the new field updates, but the objectIds of the tanks will remain the same
