### ISSUE TITLE
When you buy something for $1000, your money goes down by $2000

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#299]
**Describe the bug**
At the moment, when you buy a scanner for $1000, your money is decreased by $2000.

**To Reproduce**
1. Go to the marketplace
2. Buy something for $1000
3. Your money will decrease by $2000.

**Expected behavior**
Obviously your money should only decrease by the amount the item costs.

**Screenshots**
(difficult to show in a screenshot)

**Comment by Derplime** [comment]
Works fine for me on master. Though the sales are backwards where it's selling 1000 components for 1 money using the test data backup. Gonna have to fix the backup

**Comment by Derplime** [comment]
GIF of implementation on master
![Marketplace](https://user-images.githubusercontent.com/24559442/77857891-4bf88000-71ce-11ea-98b1-d3fb5c3e01d0.gif)

**Comment by SecondThread** [comment]
can't reproduce...
