### ISSUE TITLE
Update frontend API calls with onLoad to reduce code

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#309]
**Describe the solution you'd like**
Use the onLoad method (check getUserAPICall.js) to reduce the amount of code we need and return items correctly from the APIIntegration js files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SecondThread** [comment]
Good idea, but I'm not going to do it for a while, so I'm unassigning myself
