### ISSUE TITLE
No elo change on ties.

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#357]
**Describe the bug**
Read title. I believe this is a backend issue, but could be wrong.

**To Reproduce**
1. Have a tank get a tie.
2. View battle record to see "-0".

**Expected behavior**
They should both lose a small amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/78398497-2b129f00-75c1-11ea-9a35-7b59a020e228.png)

**Additional context**
If this is a front end issue, then let me know.

**Comment by SecondThread** [comment]
If you are the same elo, it shouldn't change. Total elo has to be conserved, so elo should only change if one player is better than the other
