### ISSUE TITLE
Better Bot Tanks

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#364]
**Describe the solution you'd like**
Improve the Casus code of the current bot tanks. Currently they're pretty dumb and most of the time will never reach you. <- Emil Task

Task for everyone: Make your own Bot Robot.

**Comment by SecondThread** [comment]
**Close range attacker:** lancer/ pulse laser. Agressive AI. **Baylor**
**Medium range attacker:** gets close, but stays at a range to attack. Shotgun maybe. Medium scanner/jammer. **Jorge**
**Medium range defender:** Moddable chassis, vulcan cannon+plasma. similar to medium range attacker, but draws enemy toward mine. **Emil**
**long range defender:** Heavy chassis, death ray, grenade launcher, heavy treads, c4 **Adam**
**sniper:** heavy chassis, death ray, missile launcher, missile tracking beacon: stay at range and snipe basically, **David**
