### ISSUE TITLE
Match doesn't resolve until fully viewed on the front end

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#378]
**Describe the bug**
If a user leaves a match while it is playing, it won't resolve until one of the users fully watch the match in the replay.

**To Reproduce**
1. Start a match and go back to battle arena.
2. Wait and logout.
3. Log back in and go to the battle record.
4. View that it says in progress.

**Expected behavior**
We can fix this in two ways:
1. Leave it as intended behavior and change in progress to unfinished (clarify in tutorials how to fix).
2. The other option is much more complicated, at least in my understanding. Maybe we can find a way to have it run in the background no matter what?

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/78502350-bd848100-772e-11ea-9f1b-ec09a9880b42.png)

**Additional context**
N/A

**Comment by SecondThread** [comment]
Yeah, this is a really hard one to actually fix. Actually running it in the background is really sketchy if they switch pages on us (idek if that is possible), and this is just kind of a side-effect of doing our processing on the front-end
