### ISSUE TITLE
Syntax error when parsing JSON

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#38]
**Describe the bug**
Web console produces the following error message when the login page is loaded:
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**To Reproduce**
Load the login page with the web console open.

**Expected behavior**
No error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/18317476/71501235-e394ae00-282e-11ea-9a96-fa12043aa9b4.png)

**Additional context**
Looks like the code touching it last was this PR:
https://github.com/RickLeinecker/Fortuna/pull/35

**Comment by JorgeVidal29** [comment]
This is a problem with what the API is returning right now. As soon as we get that approved and the api is sending back some correct data it won't be an issue
