### ISSUE TITLE
Reward user for first win of the day, add frontend toasts and UI

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#396]
**Describe the solution you'd like**
We should reward the user for the first, second, and third wins of the day. I suggestion first win = $50, second win: $100, Third win: $300. This requires adding a field to the user model for when the last time they got their win of the day was, as well as how many wins they have been given that day. It also requires adding logic in the API call to modify the money on the users side.

We also need some interesting way of handling this in the battle arena so that users know when they are given this bonus. There should be some sort of checkmarks somewhere indicating how many wins the user has gotten so far (possibly with the list of how much money they get for each win as well)

**Comment by Derplime** [comment]
I'm handling the API end of wins of the day in #274. So this should be front-end integration on that part.

**Comment by Derplime** [comment]
API was integrated a while back, so this is just a front-end task now

**Comment by blaiadam** [comment]
Fixed in MatchToast branch PR
