### ISSUE TITLE
Going to www.fortunacombat.com gives a 404

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#398]
**Describe the bug**
fortunacombat.com works fine, but for whatever reason, going to www.fortunacombat.com gives a 404.

**To Reproduce**
1. Go to www.fortunacombat.com

**Expected behavior**
The same result as going to fortunacombat.com

**Screenshots**
![image](https://user-images.githubusercontent.com/18317476/78613163-180a0400-7839-11ea-937b-9b62755536e7.png)

**Comment by Derplime** [comment]
Fixed it 👯
