### ISSUE TITLE
Implement front end handling for 3v3 battles.

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#411]
**Describe the solution you'd like**
Have toggles for 1v1 and 3v3 in Training Arena and Battle Arena. Needs to render the three tanks for the user. The size of the rendering can be changed with the TankDisplay.css.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SecondThread** [comment]
Oops, this was the wrong task
