### ISSUE TITLE
User model API

### ISSUE THREAD

**Issue by Airor4** [RickLeinecker/Fortuna#44]
**Describe the solution you'd like**
Create all api routes and controllers for the User model. This includes login and authentication which is already done but needs to be changed to accommodate the new api design pattern.

**Additional context**
'm heading towards a new design pattern that involves separating the api into routes and controllers. The routes and controllers are designed based on the models so that the code is easier to read and comprehend.

**Comment by Derplime** [comment]
Was linked with Baylor's PR but wasn't on board, so it didn't close when the PR merged.
