### ISSUE TITLE
Going from a component view to tank view in Marketplace leads to a white screen.

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#474]
**Describe the bug**
Read title.

**To Reproduce**
1. Go to Marketplace.
2. Click any of the component listings.
3. Click the tank listings.
4. View white screen.

**Expected behavior**
Should load the tanks correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/79120724-926ae480-7d61-11ea-93bd-fd0442f80415.png)

**Additional context**
N/A

**Comment by Derplime** [comment]
Adding console context:
![image](https://user-images.githubusercontent.com/24559442/79127277-9b62b280-7d6f-11ea-8a8b-849189726edb.png)

**Comment by blaiadam** [comment]
Emil, is there a null tank on the server by chance? Or one with a null ID?

**Comment by Derplime** [comment]
I'm not sure myself. I'm just posting what came up in the console when I replicated the issue.

**Comment by blaiadam** [comment]
I just tested it locally and it crashed as well. I will look into fixing it.

**Comment by blaiadam** [comment]
I am assuming that this is due to the props not updating quick enough to handle the change from components to tanks.

**Comment by SecondThread** [comment]
Can reproduce by loading the tank tab a second time
