### ISSUE TITLE
Server error on incorrect credentials

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#501]
**Describe the bug**
The message for incorrect credentials is broken

**To Reproduce**
1. Put incorrect login credentials.
2. View error

**Expected behavior**
Should print "Incorrect username or password, please try again"

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/79289976-da405780-7e98-11ea-8792-65f5aa861a73.png)

**Additional context**

**Comment by Derplime** [comment]
To add context this only happens when a username does not match one in the DB. So the conditional on the result of the username query needs to be updated.
