### ISSUE TITLE
Remove Sale Screen doesn't go to "No Active Sales" when removing last posted sale.

### ISSUE THREAD

**Issue by Derplime** [RickLeinecker/Fortuna#510]
**Describe the bug**
See Attached gif.
![Marketplace](https://user-images.githubusercontent.com/24559442/79477138-d5ce8880-7fd7-11ea-8204-85ad624745c0.gif)

**Expected behavior**
The "No Sales Listed" thing (what shows at the end of the gif) should show up after removing your last posted sale.

**Comment by blaiadam** [comment]
This worked for me. Test it again and let me know.

**Comment by Derplime** [comment]
On website:
![Marketplace](https://user-images.githubusercontent.com/24559442/79489400-331f0580-7fe9-11ea-9ac0-99c91155bdb5.gif)

**Comment by blaiadam** [comment]
Ah it must be an issue specifically with the tanks. Let me try again.
