### ISSUE TITLE
Fix headings on marketplace and sort them

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#515]
**Describe the solution you'd like**
Sort by: if one is from factory and one isn't put the one from a player on top.
If they are both from factory or both from player, sort by price.

**Describe alternatives you've considered**

**Additional context**

**Comment by Derplime** [comment]
Mind also updating the tanks that are sold by master (i.e. Casus libraries) to have similar cards to the component sales? It currently looks like this on the site when I expected the card to look like the ones when its selling components:
![image](https://user-images.githubusercontent.com/24559442/79564275-5646c500-807c-11ea-8467-d9fdfb25a393.png)
