### ISSUE TITLE
Login and Cancel Buttons are overlapping

### ISSUE THREAD

**Issue by SecondThread** [RickLeinecker/Fortuna#69]
**Describe the bug**
When you click login on the main menu, the login and cancel buttons are overlapping

**To Reproduce**
1. Go to the main screen
2. Click the login buttons

**Expected behavior**
The buttons should have some sort of padding between them,

**Screenshots**
![image](https://user-images.githubusercontent.com/18317476/73186203-56729c80-40ed-11ea-83ea-dc9d6196b676.png)

**Comment by blaiadam** [comment]
I noticed this, I'll fix it right now.

**Comment by blaiadam** [comment]
Solved in recent commit.
