### ISSUE TITLE
Casus Interpreter Default Case

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#92]
**Describe the bug**
The interpreter for Casus is lacking a default statement in a switch.

**To Reproduce**
1. Start the website.
2. After it compiles, the error should appear.

**Expected behavior**
No errors.

**Screenshots**
![Screenshot (21)](https://user-images.githubusercontent.com/42626045/74581746-f307bc00-4f80-11ea-89c9-0294cd929169.png)

**Additional context**
N/A

**Comment by SecondThread** [comment]
Thanks for catching, I'll take care of this tonight
