### ISSUE TITLE
Tank Rendering For Battle Arena and Armory

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#96]
**Describe the solution you'd like**
A component that takes the array for tanks and renders them.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by blaiadam** [comment]
Solved in UI/Design.

**Comment by Derplime** [comment]
Also add it to the game.

**Comment by blaiadam** [comment]
New issue
