### ISSUE TITLE
React App Tab Title

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#99]
**Describe the bug**
The website currently says React App on the 

**To Reproduce**
1. npm start
2. Look at tab name in the top.

**Expected behavior**
Should say FORTUNA.

**Screenshots**
![Screenshot (22)](https://user-images.githubusercontent.com/42626045/74690782-562a6600-51ae-11ea-82aa-5ca191564b53.png)

**Additional context**
N/A

**Comment by Derplime** [comment]
Would we want to update the icon as well? I believe the reference to that is in the same file where you change the "React App" title for the browser tab. Just not sure what we would use.

**Comment by blaiadam** [comment]
Maybe we can use the icon from the discord.

**Comment by Derplime** [comment]
That sounds fine. If you want to include it in your current PR that should be fine, since this issue is linked to it. Just make sure it looks fine when you view it on the browser tab.
